# alacritty.toml
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual

[terminal.shell]
program               = "/usr/bin/zsh"
args                  = [ "--login", ]

#working_directory     = "None"
#live_config_reload    = true
#ipc_socket            = true

[env]
TERM                  = "xterm-256color"

[window]
#dimensions            = { columns = 0, lines = 0 }
#position              = { x = 0, y = 0 }
padding                = { x = 2, y = 2 }
#dynamic_padding       = true
decorations            = "None"
opacity                = 0.8
blur                   = true
#startup_mode          = "Windowed"
#title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"


[scrolling]
history               = 65535
#multiplier            = 3

[font]
normal                = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold                  = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic                = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic           = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size                  = 16
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[bell]
animation             = "EaseOutExpo"
duration              = 0
color                 = "#C0C5CE"
command               = { program = "notify-send", args = ["alacritty", "bell",] }

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[hints]
#alphabet              = "jfkdls;ahgurieowpq"

#[[hints.enabled]]
#command               = "xdg-open"
## command             = "open" # On macOS
## command             = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
#hyperlinks            = true
#post_processing       = true
#persist               = false
#mouse.enabled         = true
#binding               = { key = "U", mods = "Control|Shift" }
#regex                 = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
